[package]
name = "algorithm_testing"
version = "0.1.0"
edition = "2018"
default-run = "main"

[lib]
name = "algorithms"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
lazy_static = "1.4.0"
