[package]
name = "algorithm_testing"
version = "0.1.0"
edition = "2018"

[lib]
name = "algorithms"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.9"
